---
image: python

stages:
- test
- build
- release

before_script:
- curl -O https://bootstrap.pypa.io/get-pip.py
- python get-pip.py
- pip install libfaketime tox pytest

python37:
  image: python:3.7
  stage: test
  script: tox -e py37

python38:
  image: python:3.8
  stage: test
  script: tox -e py38

python39:
  image: python:3.9
  stage: test
  script: tox -e py39

python310:
  image: python:3.10
  stage: test
  script: tox -e py310

python311:
  image: python:3.11
  stage: test
  script: tox -e py311

python312:
  image: python:3.12
  stage: test
  script: tox -e py312
